import { Provider } from '@/context/Provider'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Navbar } from '@/components/Navbar'

const roboto = Roboto({ 
  display: "swap",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: 'Sistema de rastreamento',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: React.PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
